### ISSUE TITLE
Add documentation for CSS and JavaScript in SuiteCRM

### ISSUE THREAD

**Issue by connorshea** [salesagility/SuiteDocs#263]
#### What is wrong, less clear, or missing

There isn't any documentation (as far as I can tell) about adding custom JavaScript and CSS to SuiteCRM. It's not clear how to go about adding any custom files and what needs to be done to get them to work (e.g. running 'Rebuild Compressed JS').

I'd also like to see documentation on what CSS and JavaScript frameworks the CRM uses (YUI, Bootstrap, jQuery, etc.). Just links to the actual documentation for those frameworks should be sufficient.

#### Proposed fixes and/or additions

Add documentation dedicated to writing and adding custom CSS and JavaScript to SuiteCRM.

**Comment by connorshea** [comment]
Just wanted to note here how we currently add custom CSS, since I had to look into it for the 7.10 upgrade anyway.

Current we have a custom CSS file at `custom/themes/SuiteP/custom.css`:

```css
/* Example CSS that'll give everything in the CRM a red border. */
/* Avoid using !important as much as you can. This is just for the sake of example. */
* {
  border: 1px solid red !important
}
```

And then we override the `custom/themes/SuiteP/tpls/_head.tpl` file to have some custom CSS at the top:

```smarty
<head>
  {* other head metadata and CSS files here *}
  <link href="custom/themes/SuiteP/css/custom.css" rel="stylesheet" type="text/css"/>
  <title>{$APP.LBL_BROWSER_TITLE}</title>
  {* etc. *}
</head>
```

Ideally, this'd be a more formalized system built into the CRM so we wouldn't have to use a custom `_head.tpl` at all.

The CSS will be updated whenever the `custom.css` file is updated. Unfortunately I haven't figured out how to add SCSS files to the themes themselves (short of creating a whole separate theme or modifying core CRM theme files).
